### ISSUE TITLE
Warning message: Cannot provide per-desktop overrides 

### ISSUE THREAD

**Issue by killajoe** [Antergos/antergos-gsettings#2]
`Cannot provide per-desktop overrides for localised key “visible-name” in schema “org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dXXX63-c897e6d9YYY” (override file “/usr/share/glib-2.0/schemas/90_antergos_gnome.gschema.override”); ignoring override for this key.
`
As multiple users reporting here:

https://forum.antergos.com/topic/10689/warning-message-cannot-provide-per-desktop-overrides

**Comment by karasu** [comment]
It's totally unharmful. When I have the time I will check this out.

**Comment by marciomocellin** [comment]
I have the same problem, but in pt.

` yaourt -Syua gnome-software`

`Cannot provide per-desktop overrides for localised key “visible-name” in schema “org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9” (override file “/usr/share/glib-2.0/schemas/90_antergos_gnome.gschema.override”); ignoring override for this key.`

**Comment by karasu** [comment]
@marciomocellin as I said, no problem here. It's just a configuration key that's being ignored. No harm done.
